### ISSUE TITLE
How to be sure the colorid isn't duplicate?

### ISSUE THREAD

**Issue by douxinchun** [rustq/colorid.js#7]
BTW, I see you have compared the performance of colorid and uuid. Can you provide your method of testing?

**Comment by meloalright** [comment]
> How to be sure the colorid isn't duplicate?

Just like `UUID.V4`, `ColorID` will not break the Pigeonhole Principle which means ”抽屉放苹果问题“ as well,

So they can not make sure the results never duplicate. (The algorithm of `ColorID` is actually very similar to the `UUID.V4`)

The "Pigeonhole" counts of `UUID.V4` is `(2^8^16)` = `2^128` because of the count of random `u8` is 16.

So the "Pigeonhole" counts of `ColorID` is `(2^8^12)` = `2^96` because of the count of random `u8` is 12.


> BTW, I see you have compared the performance of colorid and uuid. Can you provide your method of testing?

Yeah, the benchmark code: [benchmarks/benchmark.js](https://github.com/rustq/colorid.js/blob/main/benchmarks/benchmark.js)

The benchmark result of CI in README: [README.md?plain=1#L58](https://github.com/rustq/colorid.js/blob/main/README.md?plain=1#L58)
